import scrapy

class CrawledIndexItem(scrapy.Item):
    product_url = scrapy.Field()
    country = scrapy.Field()
    crawler_name = scrapy.Field()
    currency = scrapy.Field()
    domain_name = scrapy.Field()
    http_status = scrapy.Field()
    lang_code = scrapy.Field()
    lang_id = scrapy.Field()
    pagination_url = scrapy.Field()
    processed_date = scrapy.Field()
    retailer_id = scrapy.Field()
    retailer_name = scrapy.Field()
    scrap_datetime = scrapy.Field()
    scrap_timestamp = scrapy.Field()
    status = scrapy.Field()

class ScrappedProductItem(scrapy.Item):
    product_url = scrapy.Field()
    brand = scrapy.Field()
    breadcrumb = scrapy.Field()
    category = scrapy.Field()
    country = scrapy.Field()
    crawler_name = scrapy.Field()
    currency = scrapy.Field()
    description = scrapy.Field()
    display_technology = scrapy.Field()
    domain_name = scrapy.Field()
    ean = scrapy.Field()
    graphics_card = scrapy.Field()
    http_status = scrapy.Field()
    key_features = scrapy.Field()
    lang_code = scrapy.Field()
    memory = scrapy.Field()
    mpn = scrapy.Field()
    operating_system = scrapy.Field()
    pagination_url = scrapy.Field()
    price = scrapy.Field()
    processed_date = scrapy.Field()
    processor_brand = scrapy.Field()
    processor_generation = scrapy.Field()
    processor_model = scrapy.Field()
    processor_number_cores = scrapy.Field()
    processor_variant = scrapy.Field()
    region = scrapy.Field()
    retailer_id = scrapy.Field()
    retailer_name = scrapy.Field()
    scrap_datetime = scrapy.Field()
    scrap_timestamp = scrapy.Field()
    sku = scrapy.Field()
    status = scrapy.Field()
    thunderbolt = scrapy.Field()
    title = scrapy.Field()
    wifi = scrapy.Field()